var username;
var myName = "Muhammad Mohib Shaikh";
var message = "Hello World";
alert(message);
var name = "MOHIB";
var age = "18 years old";
var course = "Certified Mobile Application Development";

alert(name);
alert(age);
alert(course);
var pizza = "PIZZA\nPIZZ\nPIZ\nPI\nP";
alert(pizza);
var email = "shayanshaikh@gmail.com";
alert("My email address is " + email);
var book = "A smarter way to learn JavaScript";
alert("I am trying to learn from the Book " + book);
document.write("Yah! I can write HTML content through JavaScript");
var design = "▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬";
alert(design);
document.write(design);
